# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths {
  C:/Xilinx/Vivado/2014.2/progetti/WP1/ip_repo
  c:/xilinx/vivado/2014.2/progetti/wp1/ip_repo/interface_uub_1.0
} [current_fileset]
read_vhdl -library xil_defaultlib c:/xilinx/vivado/2014.2/progetti/wp1/ip_repo/interface_uub_1.0/hdl/Interface_uub_v1_0.vhd
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/xilinx/vivado/2014.2/progetti/wp1/ip_repo/interface_uub_1.0/interface_uub_v1_01_project/Interface_uub_v1_01_project.cache/wt [current_project]
set_property parent.project_dir c:/xilinx/vivado/2014.2/progetti/wp1/ip_repo/interface_uub_1.0/interface_uub_v1_01_project [current_project]
catch { write_hwdef -file Interface_uub_v1_0.hwdef }
synth_design -top Interface_uub_v1_0 -part xc7z020clg484-1
write_checkpoint Interface_uub_v1_0.dcp
report_utilization -file Interface_uub_v1_0_utilization_synth.rpt -pb Interface_uub_v1_0_utilization_synth.pb
